# Generated by Django 5.2.8 on 2025-12-21 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_crear_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='usuarioId',
            field=models.ForeignKey(db_column='organizador_id', on_delete=django.db.models.deletion.PROTECT, related_name='organizaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
