# Generated by Django 5.2.8 on 2025-11-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_imagen_update_to_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacion',
            name='participanteId',
        ),
        migrations.AddField(
            model_name='participacion',
            name='usuarioId',
            field=models.ForeignKey(blank=True, db_column='participante_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.TextField(choices=[('1', 'ADMIN'), ('2', 'PERSONAL'), ('3', 'USUARIO')], db_column='tipo_usuario'),
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
