# Generated by Django 5.2.8 on 2026-01-22 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_validaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='eventoId',
            field=models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.evento'),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='tipoUsuario',
            field=models.TextField(choices=[('1', 'Propietario'), ('2', 'Asistente'), ('3', 'Participante')], db_column='tipo_usuario'),
        ),
    ]
