# Generated by Django 5.2.8 on 2026-03-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_participacion_cascada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuarioId',
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='propietario',
            field=models.ForeignKey(db_column='organizador_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
