# Generated by Django 5.2.8 on 2026-03-26 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_mejora_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='propietario',
            field=models.ForeignKey(db_column='organizador_id', on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
    ]
