# Generated by Django 5.2.8 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_mejora_eventos_fixnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen_public_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
