# Generated by Django 5.2.8 on 2026-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_cambios_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participacion',
            name='tipoUsuario',
            field=models.TextField(choices=[('1', 'Colaborador'), ('2', 'Asistente'), ('3', 'Participante')], db_column='tipo_usuario'),
        ),
    ]
