# Generated by Django 5.2.8 on 2026-04-12 21:38

from django.db import migrations, models

def set_default_hora_inicio(apps, schema_editor):
    Evento = apps.get_model('gestion', 'Evento')
    Evento.objects.filter(hora_inicio__isnull=True).update(hora_inicio="00:00")

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_eventos_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='limite_participantes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(set_default_hora_inicio)
    ]
