# Generated by Django 5.2.8 on 2026-04-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_evento_hora_fin_evento_hora_inicio_evento_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='referencia',
            field=models.CharField(blank=True, null=True),
        ),
    ]
